export const GET_DRIVERS = "GET_DRIVERS";
export const FILTER_DRIVERS_BY_TEAM = "FILTER_DRIVERS_BY_TEAM";
export const GET_TEAMS = "GET_ALL_TEAMS";
export const FILTER_DRIVERS_BY_ORIGIN = "FILTER_DRIVERS_BY_ORIGIN";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_BIRTHDATE = "ORDER_BY_BIRTHDATE";
export const SEARCH_DRIVERS_BY_NAME = "SEARCH_DRIVERS_BY_NAME";
export const POST_DRIVER = "POST_DRIVER";
export const GET_DRIVER_BY_ID = "GET_DRIVER_BY_ID";

